"""Seeded evaluation of the verifier on synthetic solutions.

    uv run python scripts/evaluate.py                 # 1250 solutions, all conditions
    uv run python scripts/evaluate.py --solutions 100 # quick run

Writes the tables into RESULTS.md (between the GENERATED markers, so the
hand-written analysis around them is kept) and every transition to
results/transitions.jsonl for digging into failures.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from collections import Counter
from concurrent.futures import ProcessPoolExecutor
from dataclasses import asdict
from pathlib import Path

from margin_verifier.malrules import RULE_IDS
from margin_verifier.synth.evaluation import (
    CONDITIONS,
    SolutionResult,
    by,
    evaluate_index,
    metrics,
    per_noise_kind,
    per_rule,
)

ROOT = Path(__file__).resolve().parent.parent
BEGIN, END = "<!-- BEGIN GENERATED -->", "<!-- END GENERATED -->"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--solutions", type=int, default=1250)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--workers", type=int, default=min(12, os.cpu_count() or 1))
    args = parser.parse_args()

    start = time.perf_counter()
    results: list[SolutionResult] = []
    with ProcessPoolExecutor(max_workers=args.workers) as pool:
        for batch in pool.map(evaluate_index, range(args.solutions), [args.seed] * args.solutions, chunksize=8):
            results.extend(batch)
    elapsed = time.perf_counter() - start

    out_dir = ROOT / "results"
    out_dir.mkdir(exist_ok=True)
    with open(out_dir / "transitions.jsonl", "w", encoding="utf-8") as handle:
        for result in results:
            for transition in result.transitions:
                handle.write(json.dumps(asdict(transition), ensure_ascii=False) + "\n")

    report = render_report(results, args, elapsed)
    write_between_markers(ROOT / "RESULTS.md", report)
    print(report)


def render_report(results: list[SolutionResult], args, elapsed: float) -> str:
    conditions = by(results, lambda r: r.condition)
    clean = conditions["clean"]
    lines = [
        f"_Generated by `scripts/evaluate.py --solutions {args.solutions} --seed {args.seed}` "
        f"({len(clean)} solutions per condition, {elapsed:.0f}s wall time)._",
        "",
        "### Headline",
        "",
        _metrics_table({name: metrics(conditions[name]) for name in CONDITIONS if "@" not in name}),
        "",
        "### False alarms vs. OCR misread rate (held-out noise on a given share of lines)",
        "",
        _metrics_table({name: metrics(conditions[name]) for name in CONDITIONS if "@" in name}),
        "",
        "### Clean data, by problem family",
        "",
        _metrics_table({family: metrics(group) for family, group in by(clean, lambda r: r.family).items()}),
        "",
        "### Clean data, by injected mal-rule",
        "",
        _rule_table(per_rule(clean)),
        "",
        "### With anticipated OCR noise, by problem family",
        "",
        _metrics_table({f: metrics(g) for f, g in by(conditions["ocr_noise"], lambda r: r.family).items()}),
        "",
        "### With anticipated OCR noise, by mal-rule",
        "",
        _rule_table(per_rule(conditions["ocr_noise"])),
        "",
        "### Why the verifier abstained (top reasons for `uncertain`)",
        "",
        _uncertain_reasons(conditions),
        "",
        "### Correct transitions touched by each noise type",
        "",
        _noise_table({**per_noise_kind(conditions["ocr_noise"]), **per_noise_kind(conditions["held_out_noise"])}),
        "",
        "### Where the false alarms under held-out noise are",
        "",
        _false_alarm_positions(conditions),
        "",
        "### False alarms (every one, all conditions)",
        "",
        _false_alarm_list(results),
        "",
        "### Missed errors on clean data (every one)",
        "",
        _miss_list(clean),
    ]
    return "\n".join(lines)


def _fmt(value) -> str:
    if value is None:
        return "-"
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def _metrics_table(rows: dict[str, dict]) -> str:
    columns = [
        ("solutions", "solutions"),
        ("error_transitions", "error steps"),
        ("correct_transitions", "correct steps"),
        ("recall", "recall@line"),
        ("precision", "precision"),
        ("false_alarms", "false alarms"),
        ("false_alarm_rate_per_correct_transition", "FA/correct step"),
        ("false_alarm_rate_per_correct_solution", "FA/correct solution"),
        ("uncertain_rate_correct", "uncertain (correct)"),
        ("uncertain_rate_error", "uncertain (error)"),
        ("missed_as_valid", "errors called valid"),
        ("diagnosis_accuracy", "diagnosis acc."),
        ("seconds_mean", "s/step mean"),
        ("seconds_p95", "s/step p95"),
    ]
    header = "| group | " + " | ".join(title for _, title in columns) + " |"
    divider = "|---|" + "---|" * len(columns)
    body = [f"| {name} | " + " | ".join(_fmt(row[key]) for key, _ in columns) + " |" for name, row in rows.items()]
    return "\n".join([header, divider, *body])


def _rule_table(rows: dict[str, dict]) -> str:
    header = "| mal-rule | n | recall@line | uncertain | errors called valid | diagnosis acc. | most confused with |"
    divider = "|---|---|---|---|---|---|---|"
    body = [
        f"| {rule} | {r['n']} | {_fmt(r['recall'])} | {_fmt(r['uncertain'])} | {r['missed_as_valid']} "
        f"| {_fmt(r['diagnosis_accuracy'])} | {r['confused_with'] or '-'} |"
        for rule, r in rows.items()
    ]
    unused = sorted(set(RULE_IDS) - set(rows))
    note = [f"\nRules never injected in this run: {', '.join(unused)}"] if unused else []
    return "\n".join([header, divider, *body, *note])


def _noise_table(rows: dict[str, dict]) -> str:
    header = "| noise type | correct steps touched | valid | uncertain | false alarms |"
    divider = "|---|---|---|---|---|"
    body = [
        f"| {kind} | {r['correct_transitions']} | {_fmt(r['valid'])} | {_fmt(r['uncertain'])} | {r['false_alarms']} |"
        for kind, r in rows.items()
    ]
    return "\n".join([header, divider, *body])


def _uncertain_reasons(conditions: dict[str, list[SolutionResult]]) -> str:
    header = "| condition | on correct steps | on error steps |"
    divider = "|---|---|---|"
    body = []
    for name, results in conditions.items():
        cells = []
        for want_error in (False, True):
            reasons = Counter(t.reason for r in results for t in r.transitions
                              if t.is_error == want_error and t.verdict == "uncertain")
            cells.append(", ".join(f"{reason} ({count})" for reason, count in reasons.most_common(4)) or "-")
        body.append(f"| {name} | {cells[0]} | {cells[1]} |")
    return "\n".join([header, divider, *body])


def _false_alarm_positions(conditions: dict[str, list[SolutionResult]]) -> str:
    """Does the step involve the problem line (line 0) or the final line? Those have no
    neighbour on one side, so a misread there cannot be cross-checked by the next line."""
    header = "| condition | false alarms | involve line 0 | involve the final line | both | middle only |"
    divider = "|---|---|---|---|---|---|"
    body = []
    for name, results in conditions.items():
        if not name.startswith("held_out"):
            continue
        counts = Counter()
        for result in results:
            last = len(result.transitions)  # index of the final line
            for t in result.transitions:
                if t.is_error or t.verdict != "invalid":
                    continue
                counts[_position(t.step, last)] += 1
        total = sum(counts.values())
        body.append(f"| {name} | {total} | {counts['first']} | {counts['final']} | {counts['both']} | {counts['middle']} |")
    return "\n".join([header, divider, *body])


def _position(step: int, final_line: int) -> str:
    """Step `step` goes from line step-1 to line step."""
    touches_first, touches_final = step == 1, step == final_line
    if touches_first and touches_final:
        return "both"
    if touches_first:
        return "first"
    if touches_final:
        return "final"
    return "middle"


def _false_alarm_list(results: list[SolutionResult]) -> str:
    rows = []
    for result in results:
        for t in result.transitions:
            if not t.is_error and t.verdict == "invalid" and not t.condition.startswith("held_out"):
                rows.append(f"- [{t.condition}] `{t.solution}` step {t.step} ({t.reason}, {t.error_type}), "
                            f"noise={t.noise or 'none'}: `{t.lines[0]}` -> `{t.lines[1]}`")
    held_out = Counter(r.condition for r in results for t in r.transitions
                       if r.condition.startswith("held_out") and not t.is_error and t.verdict == "invalid")
    for condition, count in sorted(held_out.items()):
        rows.append(f"- [{condition}] {count} false alarms (not listed; see results/transitions.jsonl)")
    return "\n".join(rows) if rows else "- none"


def _miss_list(results: list[SolutionResult]) -> str:
    rows = []
    for result in results:
        for t in result.transitions:
            if t.is_error and t.verdict != "invalid":
                rows.append(f"- `{t.solution}` step {t.step} ({t.injected_rule}) -> {t.verdict} ({t.reason}): "
                            f"`{t.lines[0]}` -> `{t.lines[1]}`")
    return "\n".join(rows) if rows else "- none"


def write_between_markers(path: Path, generated: str) -> None:
    text = path.read_text(encoding="utf-8") if path.exists() else f"# Results\n\n{BEGIN}\n{END}\n"
    if BEGIN not in text:
        text += f"\n{BEGIN}\n{END}\n"
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    path.write_text(f"{head}{BEGIN}\n{generated}\n{END}{tail}", encoding="utf-8")


if __name__ == "__main__":
    main()
